name: Deploy

on:
  push:
    branches: [ server ]

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run build
      - run: docker restart worki
