name: server

on:
  push:
    branches: [ server ]

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Git
        uses: actions/checkout@v3

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSH_RSA }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            npm install
            npm run lint
            npm run build
            docker-compose build -d
            docker-compose up -d
